# Notes 

In [1]:
print("Hello world")

Hello world


In [ ]:
# Execute a command in jupyter notbook (nb) hit: shift+ enter
# String constants use single quotes (') or double quotes (")
# Numeric constants are as you expect



# Variables

In [3]:
x=12.2
y=5
print(x+y)

17.2


# Input

In [4]:
# We can instruct Python to pause and read data from the user using the input()  function
# The input()  function returns a string
nam = input('Who are you? ')
print('Welcome', nam)


Who are you? Ayesh
Welcome Ayesh


# Number types

In [10]:
a = 123
type(a)


int

In [11]:
b = 123.5
type(b)

float

In [12]:
c = a+ b
type(c)

float

In [13]:
# Integer division produces a floating point result
print(99.0 / 100.0)

0.99


# String Conversions

In [5]:
# You will get an error if the string does not contain numeric characters
val = '123'
type(val) # val is a string although we entered '123'

str

In [6]:
print(val + 1)# If you try to add string and numeric : get an error

TypeError: can only concatenate str (not "int") to str

In [7]:
# You can also use int() and float() to convert between strings and integers
val = int(val)

In [8]:
type(val)

int

# Conditional statement

In [15]:
x = input('Enter a number: ')

Enter a number: 7


In [20]:
x = int(x)
if x < 2:
    print( "You entered "+str(x)+", is a small number")
elif x< 10:
    print( "You entered "+str(x)+", is s medium number")
else:
    print("You entered "+str(x)+", is a lage number")

You entered 7, is s medium number


In [24]:
def myConditionalEval(x):
    if x < 2:
        print( "You entered "+str(x)+", is a small number")
    elif x< 10:
        print( "You entered "+str(x)+", is a medium number")
    else:
        print("You entered "+str(x)+", is a lage number")
  

In [25]:
myConditionalEval(6)

You entered 6, is s medium number


In [26]:
def greet(lang):
...     if lang == 'es':
...         return 'Hola'
...     elif lang == 'fr':
...         return 'Bonjour'
...     else:
...         return 'Hello'


In [28]:
print(greet('fr'),'Sally')

Bonjour Sally


# Definite Loops

In [33]:
x = [1,2,3]
for i in x:
    print("the number is "+str(i))

the number is 1
the number is 2
the number is 3


In [42]:
# Counting in a loop
def mySumOverList(x):
    mySum = 0
    for index in range(len(x)):
        mySum = mySum + x[index]
        index = index + 1
    print("averge of the values ",mySum/len(x))    
        

In [43]:
mySumOverList([2, 8 ,12, 15, 25])

averge of the values  12.4


# Lists

In [44]:
uokSubjects = ['AMAT', 'PMAT', 'PHYS', 'STAT', 'CHEM']
uokSubjects[0]

'AMAT'

In [45]:
dir(uokSubjects)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [51]:
uokSubjects.append('ELEC')
print(uokSubjects)

['AMAT', 'PMAT', 'PHYS', 'STAT', 'CHEM', 'ELEC', 'ELEC', 'ELEC']


# Dictionaries 

In [52]:
uokSubs = {}
uokSubs['AMAT'] = 60
uokSubs['PMAT'] = 120
uokSubs['PHYS'] = 67
print(uokSubs)

{'AMAT': 60, 'PMAT': 120, 'PHYS': 67}


In [53]:
# We want to change the value of the key 'PHYS'
uokSubs['PHYS'] = 65
print(uokSubs)

{'AMAT': 60, 'PMAT': 120, 'PHYS': 65}


# NumPy

In [54]:
import numpy as np

In [57]:
# Random number
# np.random.randn()
randNum = np.random.randn()
randNum

0.46905768135522646

In [59]:
# random array
randArray = np.random.randn(1,5)
randArray

array([[-0.14862903, -0.33531254, -0.34449948, -0.30167699, -1.01306177]])

In [60]:
randNum*randArray

array([[-0.06971559, -0.15728092, -0.16159013, -0.14150391, -0.47518441]])

# Broadcasting

In [61]:
a = np.random.randn(5,3)
b = np.random.randn(5,1)
a + b

array([[ 0.55287478,  0.99358771,  1.6291284 ],
       [ 0.076224  ,  0.55307578, -0.77721782],
       [ 1.01876905,  2.41979243,  0.18894435],
       [-1.01539222,  0.63882681,  0.57286045],
       [ 3.06963342,  0.12521783, -0.1539391 ]])

In [62]:
print(a)

[[ 0.67866062  1.11937355  1.75491423]
 [ 0.55629336  1.03314514 -0.29714846]
 [-0.68748515  0.71353823 -1.51730985]
 [-0.6839886   0.97023043  0.90426407]
 [ 2.46423253 -0.48018305 -0.75933999]]


In [63]:
print(b)

[[-0.12578583]
 [-0.48006936]
 [ 1.7062542 ]
 [-0.33140362]
 [ 0.60540089]]


In [65]:
c = [b, b, b]
print(c)

[array([[-0.12578583],
       [-0.48006936],
       [ 1.7062542 ],
       [-0.33140362],
       [ 0.60540089]]), array([[-0.12578583],
       [-0.48006936],
       [ 1.7062542 ],
       [-0.33140362],
       [ 0.60540089]]), array([[-0.12578583],
       [-0.48006936],
       [ 1.7062542 ],
       [-0.33140362],
       [ 0.60540089]])]
